version: "3.2"
services:
  rabbitmq-test:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-test'
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge